name: LAAKE
channels:
  - conda-forge
  - defaults
  - astropy
dependencies:
  - pip
  - python>=3.8
  - Pandoc
  - pip:
      - astropy
      - scipy
      - tqdm
      - astroquery
      - lumpy
      - pandas

